# Generated by Django 3.2 on 2022-06-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, max_length=90, null=True)),
                ('pswd', models.CharField(blank=True, max_length=100, null=True)),
                ('mgmt', models.CharField(blank=True, max_length=20, null=True)),
                ('interface', models.CharField(max_length=20)),
                ('ipaddress', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('mac', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(default=0)),
                ('enabled', models.IntegerField(default=1)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, max_length=20, null=True)),
                ('router', models.IntegerField(default=0)),
                ('apoint', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('wifi', models.IntegerField(default=1)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
